import type { EntityManager } from '@mikro-orm/postgresql'
import { sql } from 'kysely'
import type { CommandHandler } from '@open-mercato/shared/lib/commands'
import { registerCommand } from '@open-mercato/shared/lib/commands'
import { badRequest, isUniqueViolation, notFound } from '@open-mercato/shared/lib/crud/errors'
import { ChatConversation, ChatMessage, ChatParticipant } from '../data/entities'
import { dbNow } from '../lib/clock'
import { buildDirectKey } from '../lib/conversations'
import { loadChatMessages } from '../lib/messages'
import { loadOrganizationMember, type ChatScope } from '../lib/scope'
import { publishReadReceiptSafely, publishTypingSafely } from '../lib/transport'
import {
  actingUserId,
  chatTransportFrom,
  conversationAudience,
  emitConversationEvent,
  ensureOrganizationScope,
  ensureTenantScope,
  forkEm,
} from './shared'

export type EnsureDirectConversationInput = {
  tenantId: string
  organizationId: string
  userId: string
}

export type EnsureDirectConversationResult = {
  conversationId: string
  created: boolean
}

/**
 * Set only by the transport's projector, never by an HTTP caller.
 *
 * Marks a change that already happened in the messaging system, so the mirror
 * that would normally follow is suppressed — without it a receipt arriving from
 * Matrix is answered with a receipt sent back to Matrix, forever.
 *
 * `eventId` is nullable because a typing notification is not an event and has
 * no id; a receipt does, and carrying it keeps the two shapes the same.
 */
export type ChatEphemeralOrigin = { eventId: string | null }

export type MarkConversationReadInput = {
  tenantId: string
  organizationId: string
  conversationId: string
  readAt?: string
  externalOrigin?: ChatEphemeralOrigin
}

export type MarkAllConversationsReadInput = {
  tenantId: string
  organizationId: string
}

async function findDirectConversation(
  em: EntityManager,
  scope: ChatScope,
  directKey: string,
): Promise<ChatConversation | null> {
  return em.findOne(ChatConversation, {
    tenantId: scope.tenantId,
    organizationId: scope.organizationId,
    kind: 'direct',
    directKey,
    deletedAt: null,
  })
}

/**
 * Get, or create, the one canonical direct conversation between two people.
 *
 * "One canonical" is a database promise, not an application one. The unique
 * index over `(tenant_id, organization_id, direct_key)` means the read-then-write
 * below can lose a race safely: the losing insert raises 23505 and we re-read the
 * winner. Without the index, two people pressing "message" on each other at the
 * same moment would each get their own conversation and neither would see the
 * other's replies.
 */
const ensureDirectConversationCommand: CommandHandler<
  EnsureDirectConversationInput,
  EnsureDirectConversationResult
> = {
  id: 'chat.conversations.ensureDirect',
  async execute(input, ctx) {
    ensureTenantScope(ctx, input.tenantId)
    ensureOrganizationScope(ctx, input.organizationId)

    const messages = await loadChatMessages()
    const scope: ChatScope = { tenantId: input.tenantId, organizationId: input.organizationId }
    const senderUserId = await actingUserId(ctx)
    const em = forkEm(ctx)

    if (input.userId === senderUserId) throw badRequest(messages.cannotMessageSelf)

    // Both sides are checked against the same predicate. Checking only the
    // target would let an operator scoped into an organization they do not
    // belong to insert themselves into that organization's conversations.
    const caller = await loadOrganizationMember(em, scope, senderUserId)
    if (!caller) throw badRequest(messages.notOrganizationMember)

    const counterpart = await loadOrganizationMember(em, scope, input.userId)
    if (!counterpart) throw notFound(messages.recipientNotFound)

    const directKey = buildDirectKey(senderUserId, counterpart.id)

    const existing = await findDirectConversation(em, scope, directKey)
    if (existing) return { conversationId: existing.id, created: false }

    try {
      // One transaction: the conversation and both membership rows land together
      // or not at all. The id is generated by the database, so the conversation
      // is flushed first and the participants reference the value it came back
      // with.
      const conversationId = await em.transactional(async (tx) => {
        // The database's clock — see `lib/clock.ts`. A new conversation seeds
        // `last_message_at`, which orders the list, so it must come from the
        // same clock the first message's `created_at` will.
        const now = await dbNow(tx)
        const conversation = tx.create(ChatConversation, {
          tenantId: scope.tenantId,
          organizationId: scope.organizationId,
          kind: 'direct',
          directKey,
          lastMessageAt: now,
          createdAt: now,
          updatedAt: now,
        })
        tx.persist(conversation)
        await tx.flush()

        for (const userId of [senderUserId, counterpart.id]) {
          tx.persist(
            tx.create(ChatParticipant, {
              tenantId: scope.tenantId,
              organizationId: scope.organizationId,
              conversationId: conversation.id,
              userId,
              createdAt: now,
              updatedAt: now,
            }),
          )
        }
        await tx.flush()
        return conversation.id
      })

      await emitConversationEvent('chat.conversation.created', scope, [senderUserId, counterpart.id], {
        conversationId,
      })

      return { conversationId, created: true }
    } catch (error) {
      if (!isUniqueViolation(error)) throw error
      // The other side won the race. Their conversation is the canonical one, so
      // read it back on a clean fork — the losing one is rolled back.
      const winner = await findDirectConversation(forkEm(ctx), scope, directKey)
      if (!winner) throw error
      return { conversationId: winner.id, created: false }
    }
  },
}

/**
 * Advance the caller's own read cursor.
 *
 * Only the caller's participant row is touched — there is no shape of this input
 * that lets someone mark a conversation read on another person's behalf. The
 * cursor never moves backwards, so a stale tab replaying an old "I read up to
 * here" cannot resurrect messages the user has already seen elsewhere.
 */
const markConversationReadCommand: CommandHandler<MarkConversationReadInput, { lastReadAt: string }> = {
  id: 'chat.conversations.markRead',
  async execute(input, ctx) {
    ensureTenantScope(ctx, input.tenantId)
    ensureOrganizationScope(ctx, input.organizationId)

    const messages = await loadChatMessages()
    const scope: ChatScope = { tenantId: input.tenantId, organizationId: input.organizationId }
    const userId = await actingUserId(ctx)
    const em = forkEm(ctx)

    // One statement, and every rule the cursor has to obey is expressed in it:
    //
    // - `least(requested, now())` **clamps to the database clock**. Without it a
    //   client could send a far-future `readAt` — or simply run ahead of the
    //   server — and permanently suppress its own unread count, which is the
    //   same symptom as the skew this replaces.
    // - `greatest(existing, …)` keeps the cursor **monotonic**, so a stale tab
    //   replaying an old position cannot resurrect messages already seen.
    // - Doing both in the UPDATE removes the **read-modify-write race** the
    //   previous find-compare-flush had between two tabs marking read at once.
    // - `returning` doubles as the authorization check: no row means the caller
    //   is not a participant.
    const requestedAt = input.readAt ? new Date(input.readAt) : null
    const readAtParam = requestedAt && !Number.isNaN(requestedAt.getTime()) ? requestedAt : null

    const updated = await sql<{ last_read_at: Date | string }>`
      update chat_participants
         set last_read_at = greatest(
               coalesce(last_read_at, '-infinity'::timestamptz),
               least(
                 coalesce(${readAtParam}::timestamptz, date_trunc('milliseconds', now())),
                 date_trunc('milliseconds', now())
               )
             ),
             updated_at = date_trunc('milliseconds', now())
       where conversation_id = ${input.conversationId}::uuid
         and user_id = ${userId}::uuid
         and tenant_id = ${scope.tenantId}::uuid
         and organization_id = ${scope.organizationId}::uuid
      returning last_read_at
    `.execute(em.getKysely())

    const row = updated.rows[0]
    if (!row) throw notFound(messages.conversationNotFound)
    const lastReadAt = (row.last_read_at instanceof Date
      ? row.last_read_at
      : new Date(row.last_read_at)
    ).toISOString()

    // Only the reader's own sessions care — this is what clears the badge on
    // their other tabs and devices.
    await emitConversationEvent('chat.conversation.read', scope, [userId], {
      conversationId: input.conversationId,
      lastReadAt,
    })

    /**
     * Tell the room how far they have read, best-effort.
     *
     * Everyone else's view of "seen" is the point — this reader's own unread
     * count is already correct from the UPDATE above, and nothing about it
     * depends on the homeserver hearing. With the local transport it is a no-op.
     */
    const newest = input.externalOrigin
      ? null
      : await newestReadableMessageId(em, scope, input.conversationId, lastReadAt)
    if (newest) {
      await publishReadReceiptSafely(chatTransportFrom(ctx), { em: forkEm(ctx), container: ctx.container }, scope, {
        conversationId: input.conversationId,
        userId,
        messageId: newest,
      })
    }

    return { lastReadAt }
  },
}

/**
 * The newest message at or before a read cursor.
 *
 * A Matrix receipt points at an EVENT, not at a timestamp, so the cursor has to
 * be resolved to the message it corresponds to before it can be announced.
 * Deleted and system rows are excluded for the same reason the unread predicate
 * excludes them: neither is something a person read.
 */
async function newestReadableMessageId(
  em: EntityManager,
  scope: ChatScope,
  conversationId: string,
  lastReadAt: string,
): Promise<string | null> {
  const found = await em.findOne(
    ChatMessage,
    {
      conversationId,
      tenantId: scope.tenantId,
      organizationId: scope.organizationId,
      kind: 'user',
      deletedAt: null,
      createdAt: { $lte: new Date(lastReadAt) },
    },
    { orderBy: { createdAt: 'desc', id: 'desc' } },
  )
  return found?.id ?? null
}

/**
 * Catch up on everything at once.
 *
 * The same clamped, monotonic UPDATE as the single-conversation command, minus
 * the conversation filter — so "mark all read" cannot move any cursor backwards
 * either, and a caller can only ever move their own rows. `returning` names the
 * conversations that actually changed, which is what lets the caller's other
 * tabs clear exactly those badges rather than refetching the whole list.
 *
 * One statement rather than a request per conversation: clearing a full inbox
 * from the topbar would otherwise be up to `MAX_CONVERSATION_PAGE_SIZE` round
 * trips, each with its own guard and event.
 */
const markAllConversationsReadCommand: CommandHandler<
  MarkAllConversationsReadInput,
  { conversationIds: string[]; lastReadAt: string }
> = {
  id: 'chat.conversations.markAllRead',
  async execute(input, ctx) {
    ensureTenantScope(ctx, input.tenantId)
    ensureOrganizationScope(ctx, input.organizationId)

    const scope: ChatScope = { tenantId: input.tenantId, organizationId: input.organizationId }
    const userId = await actingUserId(ctx)
    const em = forkEm(ctx)

    const updated = await sql<{ conversation_id: string; last_read_at: Date | string }>`
      update chat_participants
         set last_read_at = date_trunc('milliseconds', now()),
             updated_at = date_trunc('milliseconds', now())
       where user_id = ${userId}::uuid
         and tenant_id = ${scope.tenantId}::uuid
         and organization_id = ${scope.organizationId}::uuid
         -- Only rows that would actually move, so an already-caught-up inbox is
         -- a no-op write and emits no events.
         and last_read_at is distinct from date_trunc('milliseconds', now())
         and exists (
           select 1 from chat_messages m
            where m.conversation_id = chat_participants.conversation_id
              and m.deleted_at is null
              and m.sender_user_id <> ${userId}::uuid
              and m.created_at > coalesce(chat_participants.last_read_at, '-infinity'::timestamptz)
         )
      returning conversation_id, last_read_at
    `.execute(em.getKysely())

    const rows = updated.rows
    const lastReadAt = (rows[0]?.last_read_at instanceof Date
      ? (rows[0].last_read_at as Date)
      : new Date(rows[0]?.last_read_at ?? Date.now())
    ).toISOString()
    const conversationIds = rows.map((row) => String(row.conversation_id))

    // One event per conversation, to the reader's own sessions only — the same
    // shape a single mark-read emits, so every listener already handles it.
    for (const conversationId of conversationIds) {
      await emitConversationEvent('chat.conversation.read', scope, [userId], {
        conversationId,
        lastReadAt,
      })
    }

    return { conversationIds, lastReadAt }
  },
}

registerCommand(ensureDirectConversationCommand)
registerCommand(markConversationReadCommand)
registerCommand(markAllConversationsReadCommand)

export type SetTypingInput = {
  tenantId: string
  organizationId: string
  conversationId: string
  typing: boolean
  /** Set only by the transport's projector. Suppresses the mirror. */
  externalOrigin?: ChatEphemeralOrigin
}

/**
 * Say that somebody is typing, or has stopped.
 *
 * Stores nothing, on either side. The SSE frame is the whole delivery
 * mechanism, and it goes to everyone in the conversation EXCEPT the person
 * typing — telling somebody their own keystrokes is noise, and it is also how a
 * naive client ends up rendering "you are typing" to itself.
 *
 * Membership is re-checked rather than assumed, exactly as a send re-checks it:
 * a typing notification names a person to everyone in a room, so a stale
 * participant row must not be a way to appear in a conversation you have been
 * removed from.
 */
const setTypingCommand: CommandHandler<SetTypingInput, { typing: boolean }> = {
  id: 'chat.conversations.setTyping',
  async execute(input, ctx) {
    ensureTenantScope(ctx, input.tenantId)
    ensureOrganizationScope(ctx, input.organizationId)

    const messages = await loadChatMessages()
    const scope: ChatScope = { tenantId: input.tenantId, organizationId: input.organizationId }
    const userId = await actingUserId(ctx)
    const em = forkEm(ctx)

    const participant = await em.findOne(ChatParticipant, {
      conversationId: input.conversationId,
      userId,
      tenantId: scope.tenantId,
      organizationId: scope.organizationId,
    })
    if (!participant) throw notFound(messages.conversationNotFound)

    const audience = await conversationAudience(em, scope, input.conversationId)
    const others = audience.filter((candidate) => candidate !== userId)
    if (others.length > 0) {
      await emitConversationEvent('chat.conversation.typing', scope, others, {
        conversationId: input.conversationId,
        userId,
        typing: input.typing,
      })
    }

    if (!input.externalOrigin) {
      await publishTypingSafely(chatTransportFrom(ctx), { em: forkEm(ctx), container: ctx.container }, scope, {
        conversationId: input.conversationId,
        userId,
        typing: input.typing,
      })
    }

    return { typing: input.typing }
  },
}

registerCommand(setTypingCommand)

export type SetConversationMutedInput = {
  tenantId: string
  organizationId: string
  conversationId: string
  muted: boolean
}

/**
 * Silence a conversation, or stop silencing it.
 *
 * Only the caller's own participant row moves — there is no recipient
 * parameter, so this cannot be used to mute somebody else's notifications.
 *
 * Muting suppresses notifications and nothing else: the unread count still
 * moves and the conversation still rises in the list. That separation is the
 * whole point. A mute that also hid the activity would quietly become a way to
 * lose things, and six months later nobody remembers which rooms they silenced.
 */
const setConversationMutedCommand: CommandHandler<
  SetConversationMutedInput,
  { muted: boolean }
> = {
  id: 'chat.conversations.setMuted',
  async execute(input, ctx) {
    ensureTenantScope(ctx, input.tenantId)
    ensureOrganizationScope(ctx, input.organizationId)

    const messages = await loadChatMessages()
    const scope: ChatScope = { tenantId: input.tenantId, organizationId: input.organizationId }
    const userId = await actingUserId(ctx)
    const em = forkEm(ctx)

    const participant = await em.findOne(ChatParticipant, {
      conversationId: input.conversationId,
      userId,
      tenantId: scope.tenantId,
      organizationId: scope.organizationId,
    })
    // 404 rather than 403, as everywhere else in this module: a conversation the
    // caller is not in must not be distinguishable from one that does not exist.
    if (!participant) throw notFound(messages.conversationNotFound)

    participant.mutedAt = input.muted ? await dbNow(em) : null
    await em.flush()

    // The caller's own sessions, so the toggle settles the same way on every
    // tab. Nobody else's view of the conversation changed.
    await emitConversationEvent('chat.conversation.updated', scope, [userId], {
      conversationId: input.conversationId,
    })

    return { muted: input.muted }
  },
}

registerCommand(setConversationMutedCommand)
