import { Migration } from '@mikro-orm/migrations';

/**
 * Message search: a folded copy of each body, and the indexes that make it
 * findable without reading the table.
 *
 * `search_body` holds the body with diacritics removed, case folded,
 * compatibility forms normalised and mention tokens stripped. It is written by
 * the application rather than generated by the database, because the same fold
 * has to run in three places -- the indexer, the query builder and the
 * client-side highlighter -- and only one of those can run inside Postgres. A
 * second implementation in SQL is a second implementation to drift from, and a
 * fold that disagrees between indexing and querying makes a message
 * unfindable with no error and nothing to see.
 *
 * Nullable so the backfill can run in batches against a live table. A row with
 * `null` here is not yet searchable; it is never wrong.
 *
 * Three indexes, because the three query shapes are genuinely different:
 *
 * - `search_tsv_idx` (GIN over a tsvector expression) serves tokens, phrases
 *   and `ts_rank_cd` ordering. The config is `simple` on purpose: an English
 *   stemmer applied to a mixed-language corpus mangles the languages this
 *   product is actually used in, and there is no Vietnamese, Chinese or
 *   Japanese config to switch to. Stemming is traded for correctness across
 *   languages.
 * - `search_trgm_idx` (GIN with `gin_trgm_ops`) serves typo tolerance and
 *   substring matching. It also carries Chinese and Japanese, which `simple`
 *   tokenises as one token per run because it has no segmentation. Created
 *   only when `pg_trgm` is present, so an environment that has not run the
 *   extension bootstrap still gets exact and prefix search rather than a
 *   failed migration.
 * - `conversation_search_idx` narrows to one conversation before any text
 *   matching happens, which is what makes searching within a conversation
 *   cheap regardless of how large the corpus is.
 *
 * Partial on `kind = 'user' AND deleted_at IS NULL`: system messages are
 * generated copy, and a deleted message must not be findable. Keeping the
 * predicate in the index rather than only in the query means the planner never
 * considers rows that can never be returned.
 */
export class Migration20260908090000_chat_message_search extends Migration {

  override up(): void {
    this.addSql(`alter table "chat_messages" add column "search_body" text null;`);

    this.addSql(`create index "chat_messages_search_tsv_idx" on "chat_messages" using gin (to_tsvector('simple', "search_body")) where "kind" = 'user' and "deleted_at" is null;`);

    this.addSql(`create index "chat_messages_conversation_search_idx" on "chat_messages" ("conversation_id", "created_at" desc) where "kind" = 'user' and "deleted_at" is null;`);

    // Conditional in SQL rather than in the migration class, so it needs no
    // driver access and behaves identically under every runner. An environment
    // that has not run the extension bootstrap still gets exact, phrase and
    // prefix search -- only the fuzzy and CJK-substring paths are unavailable,
    // which the search service detects and reports rather than failing.
    this.addSql(`do $$
      begin
        if exists (select 1 from pg_extension where extname = 'pg_trgm') then
          execute 'create index "chat_messages_search_trgm_idx" on "chat_messages" using gin ("search_body" gin_trgm_ops) where "kind" = ''user'' and "deleted_at" is null';
        end if;
      end
    $$;`);
  }

  override down(): void {
    this.addSql(`drop index if exists "chat_messages_search_trgm_idx";`);
    this.addSql(`drop index if exists "chat_messages_conversation_search_idx";`);
    this.addSql(`drop index if exists "chat_messages_search_tsv_idx";`);
    this.addSql(`alter table "chat_messages" drop column "search_body";`);
  }

}
