import { OptionalProps } from '@mikro-orm/core'
import { Check, Entity, Index, PrimaryKey, Property, Unique } from '@open-mercato/shared/lib/db/decorators'

/**
 * Kinds a conversation can take.
 *
 * `direct` is the 1:1 pair, identified by `directKey`. `space` is a named group
 * with explicit membership and roles. They share these three tables entirely —
 * the same messages, the same read cursors, the same events — and differ only in
 * how membership is decided and who may change it.
 */
export type ChatConversationKind = 'direct' | 'space'

/**
 * A participant's standing in a space.
 *
 * `owner` may rename the space and manage its membership; `member` may read,
 * send and reply. Direct conversations have no roles — both rows are `member`
 * and nothing reads the column.
 */
export type ChatParticipantRole = 'owner' | 'member'

/**
 * Whether a message was typed by a person or generated by a membership change.
 *
 * System rows are modelled rather than faked as authored text: they carry the
 * event and its target in their own columns, so the UI renders them from
 * translations and current display names instead of a frozen English sentence.
 */
export type ChatMessageKind = 'user' | 'system'

/** The membership changes that leave a trace in the transcript. */
export type ChatSystemEvent = 'member_added' | 'member_removed' | 'member_left' | 'space_renamed'

/** Longest space name the schema and the validators both accept. */
export const MAX_SPACE_TITLE_LENGTH = 80

/**
 * A conversation between a fixed set of people inside one organization.
 *
 * `directKey` is the canonical identity of a 1:1 pair — the two user ids sorted
 * and joined — and the unique index over it is what makes "Alice starts a chat
 * with Bob" and "Bob starts a chat with Alice" converge on one row even when
 * both requests land at the same instant. Application-level "find or create"
 * cannot promise that; a unique constraint can.
 *
 * The last-message columns are denormalized on purpose: the conversation list is
 * read far more often than it is written, and without them every row would need
 * its own "newest message" query.
 *
 * A `space` row carries a `title` and no `directKey`, so it never participates in
 * the direct-pair unique index below — one organization can hold any number of
 * spaces containing the same people. The CHECK constraint keeps the two shapes
 * mutually exclusive: without it a mis-set `kind` would produce either a space
 * nobody can name or a direct that escapes pair-uniqueness.
 */
@Entity({ tableName: 'chat_conversations' })
@Index({ name: 'chat_conversations_scope_recent_idx', properties: ['tenantId', 'organizationId', 'lastMessageAt', 'id'] })
@Index({
  name: 'chat_conversations_direct_uq',
  expression:
    `create unique index "chat_conversations_direct_uq" on "chat_conversations" ("tenant_id", "organization_id", "direct_key") where "kind" = 'direct' and "direct_key" is not null and "deleted_at" is null`,
})
@Check({
  name: 'chat_conversations_kind_shape_chk',
  expression:
    `("kind" = 'direct' and "direct_key" is not null and "title" is null) or ("kind" = 'space' and "title" is not null and "direct_key" is null)`,
})
export class ChatConversation {
  [OptionalProps]?:
    | 'kind'
    | 'directKey'
    | 'title'
    | 'createdByUserId'
    | 'lastMessageAt'
    | 'lastMessagePreview'
    | 'lastMessageSenderUserId'
    | 'createdAt'
    | 'updatedAt'
    | 'deletedAt'

  @PrimaryKey({ type: 'uuid', defaultRaw: 'gen_random_uuid()' })
  id!: string

  @Property({ name: 'tenant_id', type: 'uuid' })
  tenantId!: string

  @Property({ name: 'organization_id', type: 'uuid' })
  organizationId!: string

  @Property({ type: 'text', default: 'direct' })
  kind: ChatConversationKind = 'direct'

  @Property({ name: 'direct_key', type: 'text', nullable: true })
  directKey?: string | null

  /**
   * The space's name. Null for a direct conversation, whose title is the other
   * person and so belongs to the reader rather than to the row.
   */
  @Property({ type: 'text', nullable: true })
  title?: string | null

  /**
   * Who created the space. Null for directs — a direct belongs to the pair, and
   * whoever pressed "message" first has no standing the other lacks.
   */
  @Property({ name: 'created_by_user_id', type: 'uuid', nullable: true })
  createdByUserId?: string | null

  /**
   * Sort key for the conversation list. Seeded with the creation time rather
   * than left null, so a brand-new conversation sorts with the newest and the
   * keyset cursor compares one indexed column instead of a COALESCE.
   */
  @Property({ name: 'last_message_at', type: Date, onCreate: () => new Date() })
  lastMessageAt: Date = new Date()

  @Property({ name: 'last_message_preview', type: 'text', nullable: true })
  lastMessagePreview?: string | null

  @Property({ name: 'last_message_sender_user_id', type: 'uuid', nullable: true })
  lastMessageSenderUserId?: string | null

  @Property({ name: 'created_at', type: Date, onCreate: () => new Date() })
  createdAt: Date = new Date()

  @Property({ name: 'updated_at', type: Date, onCreate: () => new Date(), onUpdate: () => new Date(), nullable: true })
  updatedAt?: Date | null

  @Property({ name: 'deleted_at', type: Date, nullable: true })
  deletedAt?: Date | null
}

/**
 * Membership of one person in one conversation, and their read cursor.
 *
 * `lastReadAt` is the whole unread model: everything newer than it, from someone
 * else, is unread. That keeps unread state to one row per person per
 * conversation instead of one row per message per person, and it stays correct
 * across refreshes, tabs and devices because it lives on the server.
 *
 * The row's existence IS the access grant. Removing someone deletes it, which
 * ends their read access, their unread state and — because the SSE audience is
 * recomputed from these rows on every emit — their realtime delivery, in one
 * write. Their messages are untouched: those live in `chat_messages` and stay.
 */
@Entity({ tableName: 'chat_participants' })
@Unique({ name: 'chat_participants_conversation_user_uq', properties: ['conversationId', 'userId'] })
@Index({ name: 'chat_participants_scope_user_idx', properties: ['tenantId', 'organizationId', 'userId'] })
@Index({ name: 'chat_participants_conversation_idx', properties: ['conversationId'] })
@Index({
  name: 'chat_participants_owner_idx',
  expression:
    `create index "chat_participants_owner_idx" on "chat_participants" ("conversation_id") where "role" = 'owner'`,
})
export class ChatParticipant {
  [OptionalProps]?: 'role' | 'lastReadAt' | 'createdAt' | 'updatedAt'

  @PrimaryKey({ type: 'uuid', defaultRaw: 'gen_random_uuid()' })
  id!: string

  @Property({ name: 'tenant_id', type: 'uuid' })
  tenantId!: string

  @Property({ name: 'organization_id', type: 'uuid' })
  organizationId!: string

  @Property({ name: 'conversation_id', type: 'uuid' })
  conversationId!: string

  @Property({ name: 'user_id', type: 'uuid' })
  userId!: string

  /**
   * Standing in a space. Always `member` in a direct conversation, where the
   * column is written but never read.
   */
  @Property({ type: 'text', default: 'member' })
  role: ChatParticipantRole = 'member'

  @Property({ name: 'last_read_at', type: Date, nullable: true })
  lastReadAt?: Date | null

  @Property({ name: 'created_at', type: Date, onCreate: () => new Date() })
  createdAt: Date = new Date()

  @Property({ name: 'updated_at', type: Date, onCreate: () => new Date(), onUpdate: () => new Date(), nullable: true })
  updatedAt?: Date | null
}

/**
 * One turn in a conversation. Append-only: Phase 1 has no edit and no delete, so
 * the row is written once and read many times.
 *
 * `clientMessageId` is the idempotency key. A composer that retries after a
 * timeout sends the same id, and the partial unique index turns the second write
 * into a conflict the send command resolves by returning the message already
 * stored — so a flaky network cannot double-post.
 *
 * `body` is plain text and is rendered as a text node. Nothing in this module
 * parses it as HTML or markdown.
 *
 * `replyToMessageId` is a structural reference, never quoted text copied into
 * the body — so the original's author stays correct, and a reply survives the
 * original being edited or removed.
 *
 * **A reply cannot cross a conversation, and that is a database fact.** A plain
 * foreign key on `reply_to_message_id` would only prove the target exists; it
 * would happily accept a message from another space, or another organization's
 * conversation. The composite key below carries `conversation_id` on both sides,
 * so the referenced row must be in the *same* conversation — which, since a
 * conversation is already pinned to one tenant and organization, closes the
 * cross-tenant case in the same constraint. A forged id is rejected by Postgres
 * even if every application check above it were removed.
 */
@Entity({ tableName: 'chat_messages' })
@Index({ name: 'chat_messages_conversation_created_idx', properties: ['conversationId', 'createdAt'] })
@Index({ name: 'chat_messages_scope_idx', properties: ['tenantId', 'organizationId'] })
@Unique({ name: 'chat_messages_id_conversation_uq', properties: ['id', 'conversationId'] })
@Index({
  name: 'chat_messages_client_id_uq',
  expression:
    `create unique index "chat_messages_client_id_uq" on "chat_messages" ("conversation_id", "client_message_id") where "client_message_id" is not null and "deleted_at" is null`,
})
@Index({
  name: 'chat_messages_reply_idx',
  expression:
    `create index "chat_messages_reply_idx" on "chat_messages" ("reply_to_message_id") where "reply_to_message_id" is not null`,
})
export class ChatMessage {
  [OptionalProps]?:
    | 'kind'
    | 'clientMessageId'
    | 'replyToMessageId'
    | 'systemEvent'
    | 'systemTargetUserId'
    | 'createdAt'
    | 'updatedAt'
    | 'deletedAt'

  @PrimaryKey({ type: 'uuid', defaultRaw: 'gen_random_uuid()' })
  id!: string

  @Property({ name: 'tenant_id', type: 'uuid' })
  tenantId!: string

  @Property({ name: 'organization_id', type: 'uuid' })
  organizationId!: string

  @Property({ name: 'conversation_id', type: 'uuid' })
  conversationId!: string

  @Property({ name: 'sender_user_id', type: 'uuid' })
  senderUserId!: string

  /**
   * The typed text. Empty for a membership event, whose sentence is assembled
   * from `systemEvent` and the people it names — a stored English string would
   * be wrong in four of the module's five locales and would freeze a display
   * name that later changes. `space_renamed` is the exception: the new title is
   * genuine content, so it lives here.
   */
  @Property({ type: 'text' })
  body!: string

  @Property({ type: 'text', default: 'user' })
  kind: ChatMessageKind = 'user'

  /** Which membership change this row records. Null for `kind = 'user'`. */
  @Property({ name: 'system_event', type: 'text', nullable: true })
  systemEvent?: ChatSystemEvent | null

  /**
   * The person a membership event is about. The *actor* needs no column of its
   * own — `senderUserId` already carries whoever performed the change.
   */
  @Property({ name: 'system_target_user_id', type: 'uuid', nullable: true })
  systemTargetUserId?: string | null

  /** The message this one replies to. Always in the same conversation. */
  @Property({ name: 'reply_to_message_id', type: 'uuid', nullable: true })
  replyToMessageId?: string | null

  @Property({ name: 'client_message_id', type: 'text', nullable: true })
  clientMessageId?: string | null

  @Property({ name: 'created_at', type: Date, onCreate: () => new Date() })
  createdAt: Date = new Date()

  @Property({ name: 'updated_at', type: Date, onCreate: () => new Date(), onUpdate: () => new Date(), nullable: true })
  updatedAt?: Date | null

  @Property({ name: 'deleted_at', type: Date, nullable: true })
  deletedAt?: Date | null
}
