import { OptionalProps } from '@mikro-orm/core'
import { Check, Entity, Index, PrimaryKey, Property, Unique } from '@open-mercato/shared/lib/db/decorators'

/**
 * Kinds a conversation can take.
 *
 * `direct` is the 1:1 pair, identified by `directKey`. `space` is a named group
 * with explicit membership and roles. They share these three tables entirely —
 * the same messages, the same read cursors, the same events — and differ only in
 * how membership is decided and who may change it.
 */
export type ChatConversationKind = 'direct' | 'space'

/**
 * A participant's standing in a space.
 *
 * `owner` may rename the space and manage its membership; `member` may read,
 * send and reply. Direct conversations have no roles — both rows are `member`
 * and nothing reads the column.
 */
export type ChatParticipantRole = 'owner' | 'member'

/**
 * Whether a message was typed by a person or generated by a membership change.
 *
 * System rows are modelled rather than faked as authored text: they carry the
 * event and its target in their own columns, so the UI renders them from
 * translations and current display names instead of a frozen English sentence.
 */
export type ChatMessageKind = 'user' | 'system'

/** The membership changes that leave a trace in the transcript. */
export type ChatSystemEvent = 'member_added' | 'member_removed' | 'member_left' | 'space_renamed'

/** Longest space name the schema and the validators both accept. */
export const MAX_SPACE_TITLE_LENGTH = 80

/**
 * Longest reaction the schema accepts.
 *
 * An emoji is one or more code points — a family or a flag is several joined by
 * zero-width joiners — so this is a byte budget rather than a character count,
 * generous enough for any single grapheme and far too small for a sentence.
 */
export const MAX_REACTION_LENGTH = 32

/**
 * ISO-639-1 is two letters; BCP-47 with a region ("pt-BR") is five. Ten is
 * generous for both and still refuses anything that is not a language tag.
 */
export const MAX_LOCALE_LENGTH = 10

/**
 * A conversation between a fixed set of people inside one organization.
 *
 * `directKey` is the canonical identity of a 1:1 pair — the two user ids sorted
 * and joined — and the unique index over it is what makes "Alice starts a chat
 * with Bob" and "Bob starts a chat with Alice" converge on one row even when
 * both requests land at the same instant. Application-level "find or create"
 * cannot promise that; a unique constraint can.
 *
 * The last-message columns are denormalized on purpose: the conversation list is
 * read far more often than it is written, and without them every row would need
 * its own "newest message" query.
 *
 * A `space` row carries a `title` and no `directKey`, so it never participates in
 * the direct-pair unique index below — one organization can hold any number of
 * spaces containing the same people. The CHECK constraint keeps the two shapes
 * mutually exclusive: without it a mis-set `kind` would produce either a space
 * nobody can name or a direct that escapes pair-uniqueness.
 */
@Entity({ tableName: 'chat_conversations' })
@Index({ name: 'chat_conversations_scope_recent_idx', properties: ['tenantId', 'organizationId', 'lastMessageAt', 'id'] })
@Index({
  name: 'chat_conversations_direct_uq',
  expression:
    `create unique index "chat_conversations_direct_uq" on "chat_conversations" ("tenant_id", "organization_id", "direct_key") where "kind" = 'direct' and "direct_key" is not null and "deleted_at" is null`,
})
@Check({
  name: 'chat_conversations_kind_shape_chk',
  expression:
    `("kind" = 'direct' and "direct_key" is not null and "title" is null) or ("kind" = 'space' and "title" is not null and "direct_key" is null)`,
})
export class ChatConversation {
  [OptionalProps]?:
    | 'kind'
    | 'directKey'
    | 'title'
    | 'createdByUserId'
    | 'lastMessageAt'
    | 'lastMessagePreview'
    | 'lastMessageSenderUserId'
    | 'createdAt'
    | 'updatedAt'
    | 'deletedAt'

  @PrimaryKey({ type: 'uuid', defaultRaw: 'gen_random_uuid()' })
  id!: string

  @Property({ name: 'tenant_id', type: 'uuid' })
  tenantId!: string

  @Property({ name: 'organization_id', type: 'uuid' })
  organizationId!: string

  @Property({ type: 'text', default: 'direct' })
  kind: ChatConversationKind = 'direct'

  @Property({ name: 'direct_key', type: 'text', nullable: true })
  directKey?: string | null

  /**
   * The space's name. Null for a direct conversation, whose title is the other
   * person and so belongs to the reader rather than to the row.
   */
  @Property({ type: 'text', nullable: true })
  title?: string | null

  /**
   * Who created the space. Null for directs — a direct belongs to the pair, and
   * whoever pressed "message" first has no standing the other lacks.
   */
  @Property({ name: 'created_by_user_id', type: 'uuid', nullable: true })
  createdByUserId?: string | null

  /**
   * Sort key for the conversation list. Seeded with the creation time rather
   * than left null, so a brand-new conversation sorts with the newest and the
   * keyset cursor compares one indexed column instead of a COALESCE.
   */
  @Property({ name: 'last_message_at', type: Date, onCreate: () => new Date() })
  lastMessageAt: Date = new Date()

  @Property({ name: 'last_message_preview', type: 'text', nullable: true })
  lastMessagePreview?: string | null

  @Property({ name: 'last_message_sender_user_id', type: 'uuid', nullable: true })
  lastMessageSenderUserId?: string | null

  @Property({ name: 'created_at', type: Date, onCreate: () => new Date() })
  createdAt: Date = new Date()

  @Property({ name: 'updated_at', type: Date, onCreate: () => new Date(), onUpdate: () => new Date(), nullable: true })
  updatedAt?: Date | null

  @Property({ name: 'deleted_at', type: Date, nullable: true })
  deletedAt?: Date | null
}

/**
 * Membership of one person in one conversation, and their read cursor.
 *
 * `lastReadAt` is the whole unread model: everything newer than it, from someone
 * else, is unread. That keeps unread state to one row per person per
 * conversation instead of one row per message per person, and it stays correct
 * across refreshes, tabs and devices because it lives on the server.
 *
 * The row's existence IS the access grant. Removing someone deletes it, which
 * ends their read access, their unread state and — because the SSE audience is
 * recomputed from these rows on every emit — their realtime delivery, in one
 * write. Their messages are untouched: those live in `chat_messages` and stay.
 */
@Entity({ tableName: 'chat_participants' })
@Unique({ name: 'chat_participants_conversation_user_uq', properties: ['conversationId', 'userId'] })
@Index({ name: 'chat_participants_scope_user_idx', properties: ['tenantId', 'organizationId', 'userId'] })
@Index({ name: 'chat_participants_conversation_idx', properties: ['conversationId'] })
@Index({
  name: 'chat_participants_owner_idx',
  expression:
    `create index "chat_participants_owner_idx" on "chat_participants" ("conversation_id") where "role" = 'owner'`,
})
export class ChatParticipant {
  [OptionalProps]?: 'role' | 'lastReadAt' | 'createdAt' | 'updatedAt'

  @PrimaryKey({ type: 'uuid', defaultRaw: 'gen_random_uuid()' })
  id!: string

  @Property({ name: 'tenant_id', type: 'uuid' })
  tenantId!: string

  @Property({ name: 'organization_id', type: 'uuid' })
  organizationId!: string

  @Property({ name: 'conversation_id', type: 'uuid' })
  conversationId!: string

  @Property({ name: 'user_id', type: 'uuid' })
  userId!: string

  /**
   * Standing in a space. Always `member` in a direct conversation, where the
   * column is written but never read.
   */
  @Property({ type: 'text', default: 'member' })
  role: ChatParticipantRole = 'member'

  @Property({ name: 'last_read_at', type: Date, nullable: true })
  lastReadAt?: Date | null

  @Property({ name: 'created_at', type: Date, onCreate: () => new Date() })
  createdAt: Date = new Date()

  @Property({ name: 'updated_at', type: Date, onCreate: () => new Date(), onUpdate: () => new Date(), nullable: true })
  updatedAt?: Date | null
}

/**
 * One turn in a conversation. Append-only: Phase 1 has no edit and no delete, so
 * the row is written once and read many times.
 *
 * `clientMessageId` is the idempotency key. A composer that retries after a
 * timeout sends the same id, and the partial unique index turns the second write
 * into a conflict the send command resolves by returning the message already
 * stored — so a flaky network cannot double-post.
 *
 * `body` is plain text and is rendered as a text node. Nothing in this module
 * parses it as HTML or markdown.
 *
 * `replyToMessageId` is a structural reference, never quoted text copied into
 * the body — so the original's author stays correct, and a reply survives the
 * original being edited or removed.
 *
 * **A reply cannot cross a conversation, and that is a database fact.** A plain
 * foreign key on `reply_to_message_id` would only prove the target exists; it
 * would happily accept a message from another space, or another organization's
 * conversation. The composite key below carries `conversation_id` on both sides,
 * so the referenced row must be in the *same* conversation — which, since a
 * conversation is already pinned to one tenant and organization, closes the
 * cross-tenant case in the same constraint. A forged id is rejected by Postgres
 * even if every application check above it were removed.
 */
@Entity({ tableName: 'chat_messages' })
@Index({ name: 'chat_messages_conversation_created_idx', properties: ['conversationId', 'createdAt'] })
@Index({ name: 'chat_messages_scope_idx', properties: ['tenantId', 'organizationId'] })
@Unique({ name: 'chat_messages_id_conversation_uq', properties: ['id', 'conversationId'] })
@Index({
  name: 'chat_messages_client_id_uq',
  expression:
    `create unique index "chat_messages_client_id_uq" on "chat_messages" ("conversation_id", "client_message_id") where "client_message_id" is not null and "deleted_at" is null`,
})
@Index({
  name: 'chat_messages_reply_idx',
  expression:
    `create index "chat_messages_reply_idx" on "chat_messages" ("reply_to_message_id") where "reply_to_message_id" is not null`,
})
export class ChatMessage {
  [OptionalProps]?:
    | 'kind'
    | 'clientMessageId'
    | 'replyToMessageId'
    | 'mentionsEveryone'
    | 'systemEvent'
    | 'systemTargetUserId'
    | 'createdAt'
    | 'updatedAt'
    | 'deletedAt'

  @PrimaryKey({ type: 'uuid', defaultRaw: 'gen_random_uuid()' })
  id!: string

  @Property({ name: 'tenant_id', type: 'uuid' })
  tenantId!: string

  @Property({ name: 'organization_id', type: 'uuid' })
  organizationId!: string

  @Property({ name: 'conversation_id', type: 'uuid' })
  conversationId!: string

  @Property({ name: 'sender_user_id', type: 'uuid' })
  senderUserId!: string

  /**
   * The typed text. Empty for a membership event, whose sentence is assembled
   * from `systemEvent` and the people it names — a stored English string would
   * be wrong in four of the module's five locales and would freeze a display
   * name that later changes. `space_renamed` is the exception: the new title is
   * genuine content, so it lives here.
   */
  @Property({ type: 'text' })
  body!: string

  /**
   * The body folded for search: diacritics removed, case folded, compatibility
   * forms normalised, mention tokens stripped, and separator-free forms of any
   * identifier appended.
   *
   * A second column rather than a transformation at query time, because a
   * function applied to every row is a sequential scan by definition. This one
   * is indexed, so a search reads an index rather than the table.
   *
   * Written by the application through `buildSearchDocument`, not by a
   * generated column: the fold has to be identical in the indexer, the query
   * builder and the client-side highlighter, and only one of those three can
   * run inside Postgres. Nullable so the backfill can proceed in batches
   * without blocking writes -- a row with `null` here is simply not yet
   * searchable, never wrong.
   *
   * It is derived data. The original `body` is never modified.
   */
  @Property({ name: 'search_body', type: 'text', nullable: true })
  searchBody?: string | null

  @Property({ type: 'text', default: 'user' })
  kind: ChatMessageKind = 'user'

  /** Which membership change this row records. Null for `kind = 'user'`. */
  @Property({ name: 'system_event', type: 'text', nullable: true })
  systemEvent?: ChatSystemEvent | null

  /**
   * The person a membership event is about. The *actor* needs no column of its
   * own — `senderUserId` already carries whoever performed the change.
   */
  @Property({ name: 'system_target_user_id', type: 'uuid', nullable: true })
  systemTargetUserId?: string | null

  /** The message this one replies to. Always in the same conversation. */
  @Property({ name: 'reply_to_message_id', type: 'uuid', nullable: true })
  replyToMessageId?: string | null

  /**
   * Whether this message addressed the whole space.
   *
   * A flag, not a mention row per member: `@everyone` means the people in the
   * space at the moment it is read, so expanding it at send time would both
   * notify members who have since left and miss members who have since joined.
   */
  @Property({ name: 'mentions_everyone', type: Boolean, default: false })
  mentionsEveryone: boolean = false

  @Property({ name: 'client_message_id', type: 'text', nullable: true })
  clientMessageId?: string | null

  @Property({ name: 'created_at', type: Date, onCreate: () => new Date() })
  createdAt: Date = new Date()

  @Property({ name: 'updated_at', type: Date, onCreate: () => new Date(), onUpdate: () => new Date(), nullable: true })
  updatedAt?: Date | null

  @Property({ name: 'deleted_at', type: Date, nullable: true })
  deletedAt?: Date | null
}

/**
 * One person's one emoji on one message.
 *
 * Aggregation happens at read time: the row is the atom, and `👍 4` is a count
 * over four of these. Storing a counter instead would drift the moment a write
 * failed halfway, and could not answer "did I react?" without a second table.
 *
 * The unique index is what makes the toggle safe. Reacting is idempotent by
 * construction — pressing the same emoji twice removes it rather than inserting
 * a duplicate — and two tabs racing on the same reaction cannot produce two rows.
 *
 * `conversationId` is carried so the composite foreign key can pin a reaction to
 * the conversation its message lives in. Without it a forged `messageId` from
 * another space would be storable; with it Postgres refuses.
 */
@Entity({ tableName: 'chat_message_reactions' })
@Unique({ name: 'chat_message_reactions_uq', properties: ['messageId', 'userId', 'emoji'] })
@Index({ name: 'chat_message_reactions_message_idx', properties: ['messageId'] })
export class ChatMessageReaction {
  [OptionalProps]?: 'createdAt'

  @PrimaryKey({ type: 'uuid', defaultRaw: 'gen_random_uuid()' })
  id!: string

  @Property({ name: 'tenant_id', type: 'uuid' })
  tenantId!: string

  @Property({ name: 'organization_id', type: 'uuid' })
  organizationId!: string

  @Property({ name: 'message_id', type: 'uuid' })
  messageId!: string

  @Property({ name: 'conversation_id', type: 'uuid' })
  conversationId!: string

  @Property({ name: 'user_id', type: 'uuid' })
  userId!: string

  @Property({ type: 'text' })
  emoji!: string

  @Property({ name: 'created_at', type: Date, onCreate: () => new Date() })
  createdAt: Date = new Date()
}

/**
 * A message naming a person.
 *
 * The body already carries the mention as a `<@id>` token, so this table is not
 * how a mention is rendered — it is how a mention is *found*. "Which
 * conversations have an unread message naming me" is an indexed read here and a
 * scan of every message body without it.
 *
 * `@everyone` deliberately has no rows: it means the members of the space *now*,
 * so it is a flag on the message and is resolved against live membership when
 * the audience is built. Freezing it into rows at send time would notify people
 * who have since left and miss people who have since joined.
 */
/**
 * A URL somebody shared, indexed when the message was sent.
 *
 * Indexed rather than extracted on read for the same reason mentions are: the
 * Shared panel has to page through every link in a workspace's history, and
 * finding them by scanning message bodies means reading the entire transcript
 * to answer one screen of results.
 *
 * The row is derived data. The message body remains the record of what was
 * said; this is only how it is found again.
 */
@Entity({ tableName: 'chat_message_links' })
// One row per distinct URL per message. Saying the same link twice in one
// message is one thing shared, not two.
@Unique({ name: 'chat_message_links_uq', properties: ['messageId', 'url'] })
// The Shared panel's own query: this conversation's links, newest first.
@Index({
  name: 'chat_message_links_conversation_idx',
  properties: ['conversationId', 'createdAt'],
})
export class ChatMessageLink {
  [OptionalProps]?: 'createdAt'

  @PrimaryKey({ type: 'uuid', defaultRaw: 'gen_random_uuid()' })
  id!: string

  @Property({ name: 'tenant_id', type: 'uuid' })
  tenantId!: string

  @Property({ name: 'organization_id', type: 'uuid' })
  organizationId!: string

  @Property({ name: 'message_id', type: 'uuid' })
  messageId!: string

  @Property({ name: 'conversation_id', type: 'uuid' })
  conversationId!: string

  /** The URL as written, normalised only enough to deduplicate. */
  @Property({ name: 'url', type: 'text' })
  url!: string

  /** The host, so the panel can label a link without parsing on every render. */
  @Property({ name: 'host', type: 'text' })
  host!: string

  @Property({ name: 'created_at', type: Date, onCreate: () => new Date() })
  createdAt: Date = new Date()
}

@Entity({ tableName: 'chat_message_mentions' })
@Unique({ name: 'chat_message_mentions_uq', properties: ['messageId', 'mentionedUserId'] })
@Index({
  name: 'chat_message_mentions_user_idx',
  properties: ['mentionedUserId', 'conversationId'],
})
export class ChatMessageMention {
  [OptionalProps]?: 'createdAt'

  @PrimaryKey({ type: 'uuid', defaultRaw: 'gen_random_uuid()' })
  id!: string

  @Property({ name: 'tenant_id', type: 'uuid' })
  tenantId!: string

  @Property({ name: 'organization_id', type: 'uuid' })
  organizationId!: string

  @Property({ name: 'message_id', type: 'uuid' })
  messageId!: string

  @Property({ name: 'conversation_id', type: 'uuid' })
  conversationId!: string

  @Property({ name: 'mentioned_user_id', type: 'uuid' })
  mentionedUserId!: string

  @Property({ name: 'created_at', type: Date, onCreate: () => new Date() })
  createdAt: Date = new Date()
}

/**
 * A message held at the top of a conversation.
 *
 * A row rather than a flag on the message, because a pin has an author and a
 * time of its own — "who decided this matters, and when" — and because the panel
 * orders by when it was pinned, not by when the message was written.
 *
 * Unique on the pair, so pinning something already pinned is a no-op instead of
 * a second entry in the panel.
 */
@Entity({ tableName: 'chat_pinned_messages' })
@Unique({ name: 'chat_pinned_messages_uq', properties: ['conversationId', 'messageId'] })
@Index({ name: 'chat_pinned_messages_recent_idx', properties: ['conversationId', 'pinnedAt'] })
export class ChatPinnedMessage {
  [OptionalProps]?: 'pinnedAt'

  @PrimaryKey({ type: 'uuid', defaultRaw: 'gen_random_uuid()' })
  id!: string

  @Property({ name: 'tenant_id', type: 'uuid' })
  tenantId!: string

  @Property({ name: 'organization_id', type: 'uuid' })
  organizationId!: string

  @Property({ name: 'conversation_id', type: 'uuid' })
  conversationId!: string

  @Property({ name: 'message_id', type: 'uuid' })
  messageId!: string

  @Property({ name: 'pinned_by_user_id', type: 'uuid' })
  pinnedByUserId!: string

  @Property({ name: 'pinned_at', type: Date, onCreate: () => new Date() })
  pinnedAt: Date = new Date()
}

/**
 * One message rendered into one language.
 *
 * Keyed by `(message_id, target_locale)` rather than by viewer, because a
 * translation is a property of the message and the language — not of the person
 * who asked for it. Two colleagues who both read in French share the row, and
 * the second one pays nothing.
 *
 * The composite foreign key is the same guarantee reactions, mentions and pins
 * carry: a translation cannot reference a message belonging to another
 * conversation, and the database refuses it rather than trusting the caller.
 * `ON DELETE CASCADE` means a deleted message takes its translations with it,
 * so there is no orphan sweep to write or forget.
 */
@Entity({ tableName: 'chat_message_translations' })
@Unique({ name: 'chat_message_translations_uq', properties: ['messageId', 'targetLocale'] })
@Index({ name: 'chat_message_translations_message_idx', properties: ['messageId'] })
export class ChatMessageTranslation {
  [OptionalProps]?: 'createdAt'

  @PrimaryKey({ type: 'uuid', defaultRaw: 'gen_random_uuid()' })
  id!: string

  @Property({ name: 'tenant_id', type: 'uuid' })
  tenantId!: string

  @Property({ name: 'organization_id', type: 'uuid' })
  organizationId!: string

  @Property({ name: 'message_id', type: 'uuid' })
  messageId!: string

  @Property({ name: 'conversation_id', type: 'uuid' })
  conversationId!: string

  /** The language this row is written in. */
  @Property({ name: 'target_locale', type: 'text' })
  targetLocale!: string

  @Property({ type: 'text' })
  body!: string

  /**
   * What the engine detected the original to be. Recorded so the reader can be
   * told "Translated from French" rather than just handed different words, and
   * so a wrong detection is diagnosable after the fact.
   */
  @Property({ name: 'source_locale', type: 'text', nullable: true })
  sourceLocale?: string | null

  /**
   * Which engine and weights produced this. A translation is only reproducible
   * against the model that made it, so replacing the model must not silently
   * leave a mixed cache behind with no way to tell the vintages apart.
   */
  @Property({ type: 'text' })
  provider!: string

  @Property({ name: 'model_revision', type: 'text', nullable: true })
  modelRevision?: string | null

  /**
   * SHA-256 of the NFC-normalised body this was made from.
   *
   * Messages are append-only today, so a body cannot change under a
   * translation. That is a property of the current write paths, not of the
   * schema, and a cache keyed only on the id would serve the old words in
   * silence the day editing is added. Hashing rather than storing keeps a
   * deleted message's text out of this table.
   */
  @Property({ name: 'source_hash', type: 'text' })
  sourceHash!: string

  /**
   * Model, tokenizer and preprocessing, as one opaque string.
   *
   * Part of the lookup, not merely recorded: a row made by a different pipeline
   * is not an answer to the current question, so it is not a hit and the next
   * request overwrites it in place. That makes a model upgrade a lazy refresh
   * costing nothing at deploy time, instead of a cache that is silently mixed
   * forever.
   */
  @Property({ name: 'pipeline_revision', type: 'text' })
  pipelineRevision!: string

  @Property({ name: 'created_at', type: Date, onCreate: () => new Date() })
  createdAt: Date = new Date()
}

/**
 * The language a person reads chat in.
 *
 * Deliberately NOT the UI locale. `locales` is a short list of languages the
 * interface is offered in, and only `en`, `pl`, `es`, `de` and `ko` have real
 * copy behind them; the languages colleagues actually write to each other in
 * are not limited to either set. A Vietnamese speaker reads an English
 * interface whether they select `en` or the English-placeholder `vi` — so
 * deriving their reading language from the UI locale would hand them English,
 * which is the one language they did not need translating.
 *
 * One row per user per organization: the same person in two organizations may
 * reasonably read in two languages.
 */
@Entity({ tableName: 'chat_user_settings' })
@Unique({ name: 'chat_user_settings_uq', properties: ['userId', 'organizationId'] })
export class ChatUserSettings {
  [OptionalProps]?: 'createdAt' | 'updatedAt'

  @PrimaryKey({ type: 'uuid', defaultRaw: 'gen_random_uuid()' })
  id!: string

  @Property({ name: 'tenant_id', type: 'uuid' })
  tenantId!: string

  @Property({ name: 'organization_id', type: 'uuid' })
  organizationId!: string

  @Property({ name: 'user_id', type: 'uuid' })
  userId!: string

  /** ISO-639-1. Null means "follow the interface language". */
  @Property({ name: 'translation_locale', type: 'text', nullable: true })
  translationLocale?: string | null

  @Property({ name: 'created_at', type: Date, onCreate: () => new Date() })
  createdAt: Date = new Date()

  @Property({ name: 'updated_at', type: Date, onCreate: () => new Date(), onUpdate: () => new Date(), nullable: true })
  updatedAt?: Date | null
}
